PKG_FAIL_REASON+=	"CONFLICTS with python2.7"
